version: '3.7'

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres-tracker
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: quiz-project
    ports:
      - "5432:5432"